theme: osuny
_merge: deep
defaultContentLanguage: fr

params:
  logo:
    header: '/assets/images/logo-fi-blanc.png'
    footer: '/assets/images/logo-fi-blanc.png'
  posts:
    index:
      truncate_description: 0
  debug:
     productionUrl: "https://www.fi33.fr"
